import type { ControlRoomState } from "./types";

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 86_400_000).toISOString();

export const demoState: ControlRoomState = {
  statuses: [
    { id: "idea", name: "IDEA", position: 10, wipLimit: 99 },
    { id: "concept", name: "Concepto explicado", position: 20, wipLimit: 99 },
    { id: "research", name: "Investigación realizada", position: 30, wipLimit: 99 },
    { id: "development", name: "En desarrollo", position: 40, wipLimit: 3 },
    { id: "test", name: "En test", position: 50, wipLimit: 3 },
    { id: "production", name: "En producción", position: 60, wipLimit: 3 },
    { id: "sales", name: "En venta", position: 70, wipLimit: 99 }
  ],
  roles: [
    { id: "creator", name: "Creador digital" },
    { id: "finance", name: "Financiero" },
    { id: "product", name: "Producto" },
    { id: "user", name: "Usuario" }
  ],
  users: [
    { id: "laura", name: "Laura Pérez", email: "laura@equipo.local", role: "Creador digital", verified: true, verificationCode: "218934" },
    { id: "miguel", name: "Miguel Santos", email: "miguel@equipo.local", role: "Financiero", verified: false, verificationCode: "640129" },
    { id: "ana", name: "Ana Torres", email: "ana@equipo.local", role: "Producto", verified: true, verificationCode: "805421" }
  ],
  ideas: [
    {
      id: "idea-inventory",
      name: "Inventario predictivo para colmados",
      market: "Colmados y minimarkets",
      ownerId: null,
      owner: "",
      statusId: "concept",
      status: "Concepto explicado",
      value: "Alto",
      effort: "Media",
      notes: "Detectar productos que se agotan, sugerir compras y alertar sobre inventario muerto.",
      prompt: "Define un MVP de inventario predictivo para colmados con módulos, datos mínimos y pantallas clave.",
      tags: ["IA", "Inventario", "Alertas"],
      developmentProgress: 20,
      returnScore: 8,
      difficultyScore: 5,
      updatedAt: daysAgo(1)
    },
    {
      id: "idea-collections",
      name: "Cobranza con WhatsApp para talleres",
      market: "Talleres mecánicos",
      ownerId: null,
      owner: "",
      statusId: "research",
      status: "Investigación realizada",
      value: "Medio",
      effort: "Baja",
      notes: "Controlar facturas pendientes y generar mensajes de seguimiento por antigüedad.",
      prompt: "Crea un flujo de cobranza amable para talleres, con plantillas de WhatsApp y tablero de pendientes.",
      tags: ["WhatsApp", "Pagos", "CRM"],
      developmentProgress: 35,
      returnScore: 6,
      difficultyScore: 3,
      updatedAt: daysAgo(3)
    },
    {
      id: "idea-agenda",
      name: "Agenda anti-huecos para clínicas",
      market: "Clínicas pequeñas",
      ownerId: null,
      owner: "",
      statusId: "development",
      status: "En desarrollo",
      value: "Alto",
      effort: "Alta",
      notes: "Predecir cancelaciones y llenar espacios con lista de espera antes de perder ingresos.",
      prompt: "Diseña la arquitectura de una agenda anti-huecos con predicción, lista de espera y mensajes automáticos.",
      tags: ["SaaS", "Agenda", "IA"],
      developmentProgress: 50,
      returnScore: 8,
      difficultyScore: 7,
      updatedAt: daysAgo(4)
    },
    {
      id: "idea-trading-bot",
      name: "Bot de trading",
      market: "Traders independientes y equipos internos",
      ownerId: null,
      owner: "",
      statusId: "idea",
      status: "IDEA",
      value: "Alto",
      effort: "Alta",
      notes: "Sistema para analizar señales, definir reglas de entrada/salida, simular estrategias y operar con controles de riesgo.",
      prompt: "Diseña un bot de trading con backtesting, gestión de riesgo, bitácora de operaciones y alertas antes de cualquier ejecución real.",
      tags: ["Trading", "IA", "Riesgo"],
      developmentProgress: 0,
      returnScore: 7,
      difficultyScore: 9,
      updatedAt: daysAgo(5)
    },
    {
      id: "idea-ibarber",
      name: "Ibarber",
      market: "Barberías y salones pequeños",
      ownerId: null,
      owner: "",
      statusId: "concept",
      status: "Concepto explicado",
      value: "Alto",
      effort: "Media",
      notes: "App para reservas, turnos, recordatorios, catálogo de servicios, clientes frecuentes y control simple de ingresos.",
      prompt: "Estructura el MVP de Ibarber con agenda, perfiles de barberos, pagos, recordatorios y panel de métricas del negocio.",
      tags: ["Reservas", "Barbería", "SaaS"],
      developmentProgress: 18,
      returnScore: 8,
      difficultyScore: 4,
      updatedAt: daysAgo(6)
    },
    {
      id: "idea-padel",
      name: "Organizador partidos pádel",
      market: "Clubes, grupos privados y jugadores de pádel",
      ownerId: null,
      owner: "",
      statusId: "research",
      status: "Investigación realizada",
      value: "Medio",
      effort: "Media",
      notes: "Organizar partidos por nivel, disponibilidad, pistas, pagos compartidos y confirmaciones automáticas.",
      prompt: "Define pantallas y reglas para organizar partidos de pádel con ranking, disponibilidad, pagos y sustituciones.",
      tags: ["Deporte", "Reservas", "Comunidad"],
      developmentProgress: 30,
      returnScore: 6,
      difficultyScore: 5,
      updatedAt: daysAgo(7)
    },
    {
      id: "idea-agentic-daily",
      name: "Modelo agéntico diario para ideas",
      market: "Operación interna MVOG",
      ownerId: null,
      owner: "",
      statusId: "development",
      status: "En desarrollo",
      value: "Alto",
      effort: "Alta",
      notes: "Agente que revise diariamente el repositorio, proponga próximos pasos, mejore prompts y detecte ideas bloqueadas.",
      prompt: "Diseña un agente diario que lea el tablero, priorice ideas, genere tareas, actualice prompts y produzca un resumen accionable.",
      tags: ["Agentes", "Automatización", "Operaciones"],
      developmentProgress: 48,
      returnScore: 9,
      difficultyScore: 8,
      updatedAt: daysAgo(8)
    },
    {
      id: "idea-mvog-website",
      name: "Página web que venda los servicios MVOG",
      market: "Clientes potenciales de MVOG",
      ownerId: null,
      owner: "",
      statusId: "production",
      status: "En producción",
      value: "Alto",
      effort: "Media",
      notes: "Web comercial para explicar servicios, casos de uso, captación de leads y posicionamiento de MVOG.",
      prompt: "Crea una arquitectura de página web para vender servicios MVOG con propuesta de valor, secciones, CTA y embudo de contacto.",
      tags: ["Web", "Marketing", "Ventas"],
      developmentProgress: 80,
      returnScore: 8,
      difficultyScore: 4,
      updatedAt: daysAgo(9)
    },
    {
      id: "idea-instagram-casa-174",
      name: "Agente Instagram Casa 174",
      market: "Casa 174 y gestión de redes sociales",
      ownerId: null,
      owner: "",
      statusId: "concept",
      status: "Concepto explicado",
      value: "Medio",
      effort: "Media",
      notes: "Agente para planificar contenido, responder mensajes, detectar leads y mantener una línea editorial en Instagram.",
      prompt: "Diseña un agente de Instagram para Casa 174 con calendario de contenido, respuestas, clasificación de leads y métricas.",
      tags: ["Instagram", "Agentes", "Leads"],
      developmentProgress: 20,
      returnScore: 6,
      difficultyScore: 5,
      updatedAt: daysAgo(10)
    }
  ],
  activity: [
    { id: "act-4", at: daysAgo(5), text: "Se agregaron nuevas ideas estratégicas al repositorio MVOG." },
    { id: "act-1", at: daysAgo(1), text: "Inventario predictivo para colmados entró en Concepto explicado." },
    { id: "act-2", at: daysAgo(3), text: "Cobranza con WhatsApp para talleres pasó a Investigación realizada." },
    { id: "act-3", at: daysAgo(4), text: "Agenda anti-huecos para clínicas está En desarrollo." }
  ]
};
